name: BES INFERENCE CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.6.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
